### ISSUE TITLE
Should this repository be private?

### ISSUE THREAD

**Issue by rmyj** [BlakeMScurr/obsidian-notes#1]
title

**Comment by BlakeMScurr** [comment]
Good question. On the one hand, this is mostly flashcards people might find useful, on the other hand I could see myself accidentally putting personal stuff in here.

Have you found anything interesting snooping around?

**Comment by rmyj** [comment]
No, but just wanted to make sure you are aware! :)

**Comment by BlakeMScurr** [comment]
Well thank you very much for looking out for me!
